apiVersion: v1
kind: Namespace
metadata:
  name: helloworld-staging
  labels:
    name: helloworld-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld-production
  labels:
    name: helloworld-production
